bash at_defense.sh mifgsm
bash at_defense.sh vmifgsm
bash at_defense.sh vnifgsm
bash at_defense.sh rap
bash at_defense.sh gra
bash at_defense.sh pgn
bash at_defense.sh ncs
bash at_defense.sh dim
bash at_defense.sh sim
bash at_defense.sh admix
bash at_defense.sh maskblock
bash at_defense.sh dem
bash at_defense.sh decowa
bash at_defense.sh sia
bash at_defense.sh bsr
bash at_defense.sh l2t
